CREATE SEQUENCE IF NOT EXISTS SCHEDULE_WF_DEF_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

CREATE TABLE SCHEDULE_WF_DEF (
	ID bigint NOT NULL DEFAULT nextval('SCHEDULE_WF_DEF_SEQ'::regclass),
	NAME VARCHAR(45) NOT NULL,
	VERSION int NOT NULL,
	STATUS VARCHAR(45) DEFAULT NULL,
	JSON_INPUT text NOT NULL,
	CRON_EXPRESSION VARCHAR(45) NOT NULL,
	CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT SCHEDULE_WF_DEF_PKEY PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_SCHEDULE_WF_DEF
ON SCHEDULE_WF_DEF
USING BTREE (
	NAME,
	VERSION
)
TABLESPACE PG_DEFAULT;

















CREATE SEQUENCE IF NOT EXISTS MANAGER_INFO_SEQ
	INCREMENT 1
	START 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	CACHE 1;

CREATE TABLE MANAGER_INFO (
	ID bigint NOT NULL DEFAULT NEXTVAL('MANAGER_INFO_SEQ'::REGCLASS),
	NODEADDRESS VARCHAR(100) NOT NULL,
	JSON_INPUT text NOT NULL,
	CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT MANAGER_INFO_PKEY PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS MANAGER_INFO_INDEX
ON MANAGER_INFO
USING BTREE (
	NODEADDRESS
)
TABLESPACE PG_DEFAULT;















CREATE SEQUENCE IF NOT EXISTS SCHEDULED_WF_SEQ
	INCREMENT 1
	START 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	CACHE 1;


CREATE TABLE SCHEDULED_WF (
	ID bigint NOT NULL DEFAULT NEXTVAL('SCHEDULED_WF_SEQ'::REGCLASS),
	NODEADDRESS VARCHAR(100) NOT NULL,
	MANAGER_ID VARCHAR(255) NOT NULL,
	SCHEDULER_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	JSON_INPUT TEXT NOT NULL,
	CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT SCHEDULED_WF_PKEY PRIMARY KEY (ID)
);


CREATE INDEX IF NOT EXISTS SCHEDULED_ID_INDEX
	ON SCHEDULED_WF
	USING BTREE (SCHEDULER_ID)
	TABLESPACE PG_DEFAULT;


CREATE INDEX IF NOT EXISTS NAME_MANAGER_ID_NODEADDRESS_INDEX
	ON SCHEDULED_WF
	USING BTREE (
		NAME,
		MANAGER_ID,
		NODEADDRESS
	)
TABLESPACE PG_DEFAULT;












CREATE SEQUENCE IF NOT EXISTS SCHEDULED_WF_EXECUTION_SEQ
	INCREMENT 1
	START 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	CACHE 1;


CREATE TABLE SCHEDULED_WF_EXECUTION (
	ID bigint NOT NULL DEFAULT NEXTVAL('SCHEDULED_WF_EXECUTION_SEQ'::REGCLASS),
	NODEADDRESS VARCHAR(100) NOT NULL,
	MANAGER_ID VARCHAR(255) NOT NULL,
	SCHEDULER_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	JSON_INPUT TEXT NOT NULL,
	CREATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT SCHEDULED_WF_EXECUTION_PKEY PRIMARY KEY (ID)
);


CREATE INDEX IF NOT EXISTS SCHEDULED_ID_INDEX
	ON SCHEDULED_WF
	USING BTREE (SCHEDULER_ID)
	TABLESPACE PG_DEFAULT;


CREATE INDEX IF NOT EXISTS NAME_MANAGER_ID_NODEADDRESS_INDEX
	ON SCHEDULED_WF
	USING BTREE (
		NAME,
		MANAGER_ID,
		NODEADDRESS
	)
TABLESPACE PG_DEFAULT;
